[qwen30b]
hf-repo = unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:UD-Q6_K_XL
flash-attn = auto
ctx-size = 65536
cache-type-k = q8_0
cache-type-v = q8_0
n-cpu-moe = 29
temp = 0.7
min-p = 0.0
top-p = 0.8
top-k = 20
mmap = disabled

[qwen80b]
hf-repo = unsloth/Qwen3-Coder-Next-GGUF:Q4_K_S
flash-attn = auto
ctx-size = 32768
cache-type-k = q8_0
cache-type-v = q8_0
n-cpu-moe = 38
temp = 1.0
min-p = 0.01
top-p = 0.95
top-k = 40
; presence-penalty = 0.5
mmap = disabled
; mlock = enabled

[qwen7b]
hf-repo = Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q8_0
flash-attn = auto
ctx-size = 65536
cache-type-k = q8_0
cache-type-v = q8_0
mmap = disabled

[nomic-embed]
hf-repo = nomic-ai/nomic-embed-text-v2-moe-GGUF:F32
embeddings = true

[qwen-rerank]
hf-repo = ggml-org/Qwen3-Reranker-0.6B-Q8_0-GGUF

[fast-apply]
hf-repo = Kortix/FastApply-1.5B-v1.0_GGUF:Q4_K_M
